server.port: 8080

#configurações para o banco de dados MySql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        type: trace


#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username:
#    password:
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true